<?php
/**
 * Recurring event registration link helpers.
 *
 * @package Event_Organiser_Extras
 */

if ( ! defined( 'WPINC' ) ) {
	die;
}

/**
 * Returns limited recurring register link markup for an event.
 *
 * CiviCRM Event Organiser generates the links. EOX only decides how many active
 * recurring occurrence links are shown.
 *
 * @param int $event_id Event post ID.
 * @return string
 */
function eox_get_recurring_register_links_markup( $event_id ) {
	$event_id = (int) $event_id;

	if ( ! $event_id || ! eo_recurs( $event_id ) ) {
		return '';
	}

	if ( ! function_exists( 'civicrm_event_organiser_get_register_links' ) || ! function_exists( 'civicrm_eo' ) ) {
		return '';
	}

	$links = eox_get_active_recurring_register_links( $event_id );
	$links = eox_limit_recurring_register_links( $links, $event_id );

	return eox_render_register_links( $links );
}

/**
 * Return active recurring registration links generated by CiviCRM Event Organiser.
 *
 * @param int $event_id Event post ID.
 * @return array Active links.
 */
function eox_get_active_recurring_register_links( $event_id ) {
	$links_data = civicrm_event_organiser_get_register_links( $event_id );
	$links      = array();

	foreach ( $links_data as $civi_event_id => $link_data ) {
		if ( empty( $link_data['link'] ) || empty( $link_data['meta'] ) || ! in_array( 'active', $link_data['meta'], true ) ) {
			continue;
		}

		$occurrence_id = civicrm_eo()->mapping->get_eo_occurrence_id_by_civi_event_id( (int) $civi_event_id );

		if ( empty( $occurrence_id ) ) {
			continue;
		}

		$timestamp = eo_get_the_start( 'U', $event_id, $occurrence_id );

		if ( empty( $timestamp ) ) {
			continue;
		}

		$links[] = array(
			'link'      => $link_data['link'],
			'timestamp' => (int) $timestamp,
		);
	}

	usort(
		$links,
		function ( $a, $b ) {
			return $a['timestamp'] <=> $b['timestamp'];
		}
	);

	return $links;
}

/**
 * Apply recurring registration link display rules.
 *
 * @param array $links Active recurring registration links.
 * @param int   $event_id Event post ID.
 * @return array Filtered links.
 */
function eox_limit_recurring_register_links( $links, $event_id ) {
	/**
	 * Filters how recurring registration links are displayed.
	 *
	 * Accepted values are "next", "all", and "limit".
	 *
	 * @param string $display_mode Display mode.
	 * @param int    $event_id Event post ID.
	 */
	$display_mode = apply_filters( 'eox/register_links/recurring/display_mode', 'next', $event_id );

	if ( 'all' === $display_mode ) {
		return $links;
	}

	if ( 'limit' === $display_mode ) {
		/**
		 * Filters how many recurring registration links are displayed in limit mode.
		 *
		 * @param int $limit Number of links to display.
		 * @param int $event_id Event post ID.
		 */
		$limit = (int) apply_filters( 'eox/register_links/recurring/limit', 3, $event_id );

		return array_slice( $links, 0, max( 1, $limit ) );
	}

	return array_slice( $links, 0, 1 );
}

/**
 * Render registration links.
 *
 * @param array $links Registration link data.
 * @return string Registration link markup.
 */
function eox_render_register_links( $links ) {
	if ( empty( $links ) ) {
		return '';
	}

	$markup = wp_list_pluck( $links, 'link' );

	if ( 1 === count( $markup ) ) {
		return reset( $markup );
	}

	$list = implode( '</li>' . "\n" . '<li class="civicrm-event-register-link">', $markup );
	$list = '<li class="civicrm-event-register-link">' . $list . '</li>' . "\n";

	return '<ul class="civicrm-event-register-links">' . $list . '</ul>';
}
